site_name: Ryan Abrego Docs
site_url: https//ryanabrego.github.io/MKDocs/
repo_url: https//:github.com/ryanabrego/MKDocs
repo_name: GitHub

theme: 
  name: mkdocs

nav: 
  - Home: index.md
  - About: about.md
  - FAQ: faq.md
  - Getting_Started: gettings_started.md

markdown_extensions:
  - toc:

    permalink: true
  - tables
  - admonition

plugins:
  - search

