site_name: Ryan Abrego Docs
site_url: https://ryanabrego.github.io/MKDocs/
repo_url: https://github.com/ryanabrego/MKDocs
repo_name: GitHub

theme: 
  name: mkdocs

nav: 
  - Home: index.md
  - About: about.md
  - FAQ: faq.md
  - Getting_Started: getting_started.md

plugins:
  - search

