site_name: Ryan Abrego Docs
.mdsite_url: https://ryanabrego.github.io/MKDocs/
repo_url: https://github.com/ryanabrego/MKDocs
repo_name: GitHub

theme: 
  name: material

nav: 
  - Home: index.md
  - Portfolio:
      - API Documentation: portfolio/api-documentation.md
      - Docs-as-Code Projects: portfolio/docs-as-code.md
      - Python & Automation: portfolio/python.md
      - UI Help & Guides: portfolio/help-systems.md
  - Leadership & Strategy:
      - Team Management: leadership/management.md
      - Agile and DevOps: leadership/agile.md
      - Content Strategy: leadership/strategy.md
  - Services: services.md
  - Contact: contact.md

  
  

plugins:
  - search

